# .github/workflows/deploy.yml
name: Deploy to Server via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & restart on server
    runs-on: ubuntu-latest

    steps:
      # 1) Check out repo so other actions (if any) can read it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Start SSH agent & add your private key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 3) SSH into your server and run the deploy script
      - name: Pull, install, build, restart
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e                       # stop on first error
            echo "→ Switching to project dir"
            cd ${{ secrets.SSH_DIR }}

            echo "→ Resetting local changes (optional)"
            git reset --hard

            echo "→ Pulling latest code"
            git pull origin ${{ secrets.SSH_BRANCH }}

            echo "→ Installing dependencies"
            if [ -f package-lock.json ]; then
              npm ci --silent            # clean install for CI
            else
              npm install --silent
            fi

            echo "→ Building project"
            npm run build

            echo "→ Restarting app with PM2"
            # Adjust the name or ecosystem file as needed
            pm2 reload ecosystem.config.js --only app || pm2 start ecosystem.config.js --only app

            echo "✅ Deploy complete"
          EOF
