name: Deploy to Server via SSH (robust)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "# Try to fetch the host key with timeout"
          if ssh-keyscan -T 30 -H "$SSH_HOST" >> ~/.ssh/known_hosts 2>/dev/null; then
            echo "✅ Successfully added host key to known_hosts"
          else
            echo "❌ Failed to get host key via ssh-keyscan"
          fi
          echo "Current known_hosts content:"
          cat ~/.ssh/known_hosts

      - name: Test SSH connection
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo "# Test basic SSH connection"
          if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o BatchMode=yes "$SSH_USER@$SSH_HOST" "echo 'SSH connection successful'"; then
            echo "✅ SSH connection successful"
          else
            echo "❌ SSH connection failed"
            echo "This could be due to:"
            echo "- Incorrect SSH key"
            exit 1
          fi

      - name: Deploy to server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo "### Connecting to server ###"
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 "$SSH_USER@$SSH_HOST" "
            cd /path/to/app || { echo '❌ Target directory does not exist'; exit 1; }
            [ -d .git ] || { echo '❌ Not a git repository'; exit 1; }
            echo '→ Restarting with PM2'
            if pm2 reload ecosystem.config.js --only app; then
              echo '✅ PM2 reload successful'
            else
              echo '⚠️ PM2 reload failed, trying start...'
              pm2 start ecosystem.config.js --only app
            fi
          "
